language: go

go:
  - 1.3


before_script:
  - sudo apt-get install -y libjna-java python-pip
  - sudo pip install cql PyYAML six
  - go get code.google.com/p/go.tools/cmd/vet

script:
  - go vet .

notifications:
  - email: false
